services:
  - type: web
    name: backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/dockerfileProduction
    dockerContext: ./backend

databases:
  - name: db_n2ly
    plan: free
    region: frankfurt
    postgresMajorVersion: "16"
