name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Run tests in docker-compose environment
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install backend dependencies
        run: |
          cd backend
          npm install
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
          PGP_URL: ${{ secrets.PGP_URL }}
          PGP_URL_ADMIN: ${{ secrets.PGP_URL_ADMIN }}
          PORT: ${{ secrets.PORT }}
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
          CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}
          ORIGIN_URL: ${{ secrets.ORIGIN_URL }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_BASE_URL_IMG: ${{ secrets.VITE_BASE_URL_IMG }}
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          DOMAIN: ${{ secrets.DOMAIN }}

      - name: Set tests environment
        run: |
          cd tests
        env:
          PGP_URL_ADMIN: ${{ secrets.PGP_URL_ADMIN }}
          PGP_URL: ${{ secrets.PGP_URL }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          ORIGIN_URL: ${{ secrets.ORIGIN_URL }}
          DOMAIN: ${{ secrets.DOMAIN }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env
          echo "PGP_URL=${{ secrets.PGP_URL }}" >> .env
          echo "PGP_URL_ADMIN=${{ secrets.PGP_URL_ADMIN }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "CLOUD_NAME=${{ secrets.CLOUD_NAME }}" >> .env
          echo "CLOUD_API_KEY=${{ secrets.CLOUD_API_KEY }}" >> .env
          echo "CLOUD_API_SECRET=${{ secrets.CLOUD_API_SECRET }}" >> .env
          echo "ORIGIN_URL=${{ secrets.ORIGIN_URL }}" >> .env

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from ui-tests
        continue-on-error: true

      - name: Parse test results
        id: parse-test-results
        run: |
          # Анализируем результаты тестов
          results=$(cat test-results.txt)
          unexpected=$(echo "$results" | grep -oP '"unexpected": \K\d+')
          echo "Unexpected tests: $unexpected"
          echo "unexpected=$unexpected" >> $GITHUB_ENV

          # Считаем количество неожиданных тестов
          test_failures=$(echo "$results" | grep -oP '"unexpected": \K\d+')
          echo "Failed tests: $test_failures"

          # Условие для остановки пайплайна
          if [ "$test_failures" -gt 5 ]; then
            echo "Too many tests failed ($test_failures). Stopping pipeline."
            exit 1
          fi

  # Step 2: Build and push frontend image
  build:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() || failure() }} && ${{ env.unexpected <= 5 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend image
        run: docker build -t itqa47/frontend:latest ./frontend

      - name: Push frontend image to Docker Hub
        run: docker push itqa47/frontend:latest

  # Step 3: Deploy to Render
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "serviceId": "srv-cs9bl5aj1k6c73flgcdg",
                "branch": "main"
              }' \
          https://api.render.com/v1/services/srv-cs9bl5aj1k6c73flgcdg/deploys
