name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Run tests in docker-compose environment
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up

  # Step 2: Build and push frontend image
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend image
        run: docker build -t itqa47/frontend:latest ./frontend

      - name: Push frontend image to Docker Hub
        run: docker push itqa47/frontend:latest

  # Step 3: Deploy to Render
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "serviceId": "srv-cs9bl5aj1k6c73flgcdg",
                "branch": "main"
              }' \
          https://api.render.com/v1/services/srv-cs9bl5aj1k6c73flgcdg/deploys
